name = "redirect"
compatibility_date = "2023-01-20"
main = "workers-site/index.js"

account_id = "760b904f6f45db834805898d2d33f89e"
workers_dev = true

kv_namespaces = [
    { binding = "SHORTEN", id = "ID_HERE", preview_id = "PREVIEW_ID_HERE" }
]

[site]
bucket = "./public"
